"""entry topic

Thêm entries.topic: chủ đề của mục từ (vd. "Gia đình"), dùng cho kho hệ thống; từ tự tạo để trống.

Revision ID: 423213d05ebd
Revises: 26ca8c918f11
Create Date: 2026-10-03 17:48:32.480527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423213d05ebd'
down_revision: Union[str, Sequence[str], None] = '26ca8c918f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('topic', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'topic')
    # ### end Alembic commands ###
