"""Học Viện: units, unit_entries, tiến độ bài/chặng/cấp, boss_attempts, topic_practice_log, user_stats,
daily_checks, user_daily_activity, spin_grants; study_sessions thêm kind, ref_id, result (course_id được rỗng).

Revision ID: a027e19df0ee
Revises: 423213d05ebd
Create Date: 2026-10-04 09:39:34.810442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a027e19df0ee'
down_revision: Union[str, Sequence[str], None] = '423213d05ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'passed', 'partial', 'exempt', name='daily_check_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_checks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_checks')),
    sa.UniqueConstraint('user_id', 'local_date', name=op.f('uq_daily_checks_user_id_local_date'))
    )
    op.create_index(op.f('ix_daily_checks_user_id'), 'daily_checks', ['user_id'], unique=False)
    op.create_table('spin_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('normal', 'special', name='spin_kind', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('reason', sa.Enum('milestone', 'rank_up', 'boss', 'streak', name='spin_reason', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('ref', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_spin_grants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spin_grants')),
    sa.UniqueConstraint('user_id', 'reason', 'ref', name=op.f('uq_spin_grants_user_id_reason_ref'))
    )
    op.create_index(op.f('ix_spin_grants_user_id'), 'spin_grants', ['user_id'], unique=False)
    op.create_table('user_daily_activity',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('new_words', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reviews', sa.Integer(), server_default='0', nullable=False),
    sa.Column('correct', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_daily_activity_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'local_date', name=op.f('pk_user_daily_activity'))
    )
    op.create_table('user_level_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('locked', 'unlocked', 'completed', name='progress_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('boss_best', sa.Integer(), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('boss_won_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name=op.f('fk_user_level_progress_level_id_levels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_level_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'level_id', name=op.f('pk_user_level_progress'))
    )
    op.create_index(op.f('ix_user_level_progress_level_id'), 'user_level_progress', ['level_id'], unique=False)
    op.create_table('user_stats',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('current_rank', sa.String(length=16), server_default='tan_binh', nullable=False),
    sa.Column('highest_rank', sa.String(length=16), server_default='tan_binh', nullable=False),
    sa.Column('rank_shaky_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rank_shaky_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('streak_current', sa.Integer(), server_default='0', nullable=False),
    sa.Column('streak_best', sa.Integer(), server_default='0', nullable=False),
    sa.Column('streak_last_date', sa.Date(), nullable=True),
    sa.Column('max_spin_milestone', sa.Integer(), server_default='0', nullable=False),
    sa.Column('spins_normal', sa.Integer(), server_default='0', nullable=False),
    sa.Column('spins_special', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_stats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_stats'))
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_units_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units')),
    sa.UniqueConstraint('topic_id', 'position', name=op.f('uq_units_topic_id_position'))
    )
    op.create_index(op.f('ix_units_topic_id'), 'units', ['topic_id'], unique=False)
    op.create_table('user_topic_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('locked', 'unlocked', 'completed', name='progress_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('topic_test_best', sa.Integer(), nullable=True),
    sa.Column('topic_test_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stamped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_user_topic_progress_topic_id_topics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_topic_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'topic_id', name=op.f('pk_user_topic_progress'))
    )
    op.create_index(op.f('ix_user_topic_progress_topic_id'), 'user_topic_progress', ['topic_id'], unique=False)
    op.create_table('boss_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('weak_topic_ids', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('topic_accuracy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name=op.f('fk_boss_attempts_level_id_levels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], name=op.f('fk_boss_attempts_session_id_study_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_boss_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boss_attempts')),
    sa.UniqueConstraint('session_id', name=op.f('uq_boss_attempts_session_id'))
    )
    op.create_index('ix_boss_attempts_user_level_created', 'boss_attempts', ['user_id', 'level_id', 'created_at'], unique=False)
    op.create_table('unit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], name=op.f('fk_unit_entries_entry_id_entries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_unit_entries_unit_id_units'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unit_entries')),
    sa.UniqueConstraint('unit_id', 'entry_id', name=op.f('uq_unit_entries_unit_id_entry_id'))
    )
    op.create_index(op.f('ix_unit_entries_entry_id'), 'unit_entries', ['entry_id'], unique=False)
    op.create_index(op.f('ix_unit_entries_unit_id'), 'unit_entries', ['unit_id'], unique=False)
    op.create_table('user_unit_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('locked', 'unlocked', 'completed', name='progress_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('best_score', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_user_unit_progress_unit_id_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_unit_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'unit_id', name=op.f('pk_user_unit_progress'))
    )
    op.create_index(op.f('ix_user_unit_progress_unit_id'), 'user_unit_progress', ['unit_id'], unique=False)
    op.create_table('topic_practice_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('boss_attempt_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['boss_attempt_id'], ['boss_attempts.id'], name=op.f('fk_topic_practice_log_boss_attempt_id_boss_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], name=op.f('fk_topic_practice_log_session_id_study_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_topic_practice_log_topic_id_topics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_topic_practice_log_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_practice_log'))
    )
    op.create_index(op.f('ix_topic_practice_log_boss_attempt_id'), 'topic_practice_log', ['boss_attempt_id'], unique=False)
    op.create_index(op.f('ix_topic_practice_log_user_id'), 'topic_practice_log', ['user_id'], unique=False)
    op.add_column('study_sessions', sa.Column('kind', sa.Enum('course', 'unit_learn', 'unit_test', 'topic_test', 'topic_practice', 'boss', 'review', name='session_kind', native_enum=False, create_constraint=True, length=16), server_default='course', nullable=False))
    op.add_column('study_sessions', sa.Column('ref_id', sa.Integer(), nullable=True))
    op.add_column('study_sessions', sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('study_sessions', 'course_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_sessions', 'course_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('study_sessions', 'result')
    op.drop_column('study_sessions', 'ref_id')
    op.drop_column('study_sessions', 'kind')
    op.drop_index(op.f('ix_topic_practice_log_user_id'), table_name='topic_practice_log')
    op.drop_index(op.f('ix_topic_practice_log_boss_attempt_id'), table_name='topic_practice_log')
    op.drop_table('topic_practice_log')
    op.drop_index(op.f('ix_user_unit_progress_unit_id'), table_name='user_unit_progress')
    op.drop_table('user_unit_progress')
    op.drop_index(op.f('ix_unit_entries_unit_id'), table_name='unit_entries')
    op.drop_index(op.f('ix_unit_entries_entry_id'), table_name='unit_entries')
    op.drop_table('unit_entries')
    op.drop_index('ix_boss_attempts_user_level_created', table_name='boss_attempts')
    op.drop_table('boss_attempts')
    op.drop_index(op.f('ix_user_topic_progress_topic_id'), table_name='user_topic_progress')
    op.drop_table('user_topic_progress')
    op.drop_index(op.f('ix_units_topic_id'), table_name='units')
    op.drop_table('units')
    op.drop_table('user_stats')
    op.drop_index(op.f('ix_user_level_progress_level_id'), table_name='user_level_progress')
    op.drop_table('user_level_progress')
    op.drop_table('user_daily_activity')
    op.drop_index(op.f('ix_spin_grants_user_id'), table_name='spin_grants')
    op.drop_table('spin_grants')
    op.drop_index(op.f('ix_daily_checks_user_id'), table_name='daily_checks')
    op.drop_table('daily_checks')
    # ### end Alembic commands ###
