"""lapse count

Thêm user_entry_progress.lapse_count: số lần trả lời sai (mỗi lần sai lịch SRS đặt lại về khoảng ngắn nhất).

Revision ID: 26ca8c918f11
Revises: 982bfc5a3ea8
Create Date: 2026-10-03 17:38:18.487564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ca8c918f11'
down_revision: Union[str, Sequence[str], None] = '982bfc5a3ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_entry_progress', sa.Column('lapse_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_entry_progress', 'lapse_count')
    # ### end Alembic commands ###
