"""entries progress and my courses

Kho mục từ (từ hệ thống + từ tự tạo của người dùng), tiến độ từng từ (SRS, đã thuộc), nhật ký trả lời,
"Khóa học của tôi" (khóa học, mục từ trong khóa, phiên học), hàng đợi phát âm; bộ đếm từ đã thuộc trên users.

Revision ID: 982bfc5a3ea8
Revises: f840a8b6c90f
Create Date: 2026-10-03 16:50:19.817112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '982bfc5a3ea8'
down_revision: Union[str, Sequence[str], None] = 'f840a8b6c90f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headword', sa.String(length=100), nullable=False),
    sa.Column('entry_type', sa.Enum('word', 'collocation', 'phrasal_verb', 'idiom', name='entry_type', native_enum=False, create_constraint=True, length=16), server_default='word', nullable=False),
    sa.Column('pos', sa.String(length=32), nullable=True),
    sa.Column('ipa', sa.String(length=100), nullable=True),
    sa.Column('audio_url', sa.String(length=512), nullable=True),
    sa.Column('meaning_vi', sa.String(length=300), nullable=False),
    sa.Column('definition_en', sa.Text(), nullable=True),
    sa.Column('example', sa.String(length=500), nullable=True),
    sa.Column('collocations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('word_family', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('cefr', sa.String(length=2), nullable=True),
    sa.Column('exam_tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('draft', 'approved', name='entry_status', native_enum=False, create_constraint=True, length=16), server_default='draft', nullable=False),
    sa.Column('source', sa.Enum('system', 'user', name='entry_source', native_enum=False, create_constraint=True, length=16), server_default='system', nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(source = 'system' AND owner_user_id IS NULL) OR (source = 'user' AND owner_user_id IS NOT NULL)", name=op.f('ck_entries_owner_matches_source')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_entries_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entries'))
    )
    op.create_index('ix_entries_headword_lower', 'entries', [sa.literal_column('lower(headword)')], unique=False)
    op.create_index(op.f('ix_entries_owner_user_id'), 'entries', ['owner_user_id'], unique=False)
    op.create_index('uq_entries_owner_headword_lower', 'entries', ['owner_user_id', sa.literal_column('lower(headword)')], unique=True, postgresql_where=sa.text("source = 'user'"))
    op.create_table('user_courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'shared', name='course_visibility', native_enum=False, create_constraint=True, length=16), server_default='private', nullable=False),
    sa.Column('word_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_courses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_courses'))
    )
    op.create_index(op.f('ix_user_courses_user_id'), 'user_courses', ['user_id'], unique=False)
    op.create_table('audio_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'done', 'failed', name='audio_job_status', native_enum=False, create_constraint=True, length=16), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], name=op.f('fk_audio_jobs_entry_id_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_jobs'))
    )
    op.create_index(op.f('ix_audio_jobs_entry_id'), 'audio_jobs', ['entry_id'], unique=False)
    op.create_table('review_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], name=op.f('fk_review_logs_entry_id_entries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_review_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_logs'))
    )
    op.create_index(op.f('ix_review_logs_entry_id'), 'review_logs', ['entry_id'], unique=False)
    op.create_index('ix_review_logs_user_answered', 'review_logs', ['user_id', 'answered_at'], unique=False)
    op.create_table('study_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('learn', 'review', 'quick', 'hard', 'test', name='study_mode', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['user_courses.id'], name=op.f('fk_study_sessions_course_id_user_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_sessions'))
    )
    op.create_index(op.f('ix_study_sessions_course_id'), 'study_sessions', ['course_id'], unique=False)
    op.create_index(op.f('ix_study_sessions_user_id'), 'study_sessions', ['user_id'], unique=False)
    op.create_table('user_course_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('personal_note', sa.String(length=300), nullable=True),
    sa.Column('is_starred', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['user_courses.id'], name=op.f('fk_user_course_entries_course_id_user_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], name=op.f('fk_user_course_entries_entry_id_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_course_entries')),
    sa.UniqueConstraint('course_id', 'entry_id', name=op.f('uq_user_course_entries_course_id_entry_id'))
    )
    op.create_index(op.f('ix_user_course_entries_course_id'), 'user_course_entries', ['course_id'], unique=False)
    op.create_index(op.f('ix_user_course_entries_entry_id'), 'user_course_entries', ['entry_id'], unique=False)
    op.create_table('user_entry_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'learning', 'mastered', 'forgotten', name='entry_state', native_enum=False, create_constraint=True, length=16), server_default='new', nullable=False),
    sa.Column('ease', sa.Float(), server_default='2.5', nullable=False),
    sa.Column('interval_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('repetitions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('strong_days', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('last_strong_day', sa.Date(), nullable=True),
    sa.Column('correct_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wrong_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_day', sa.Date(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mastered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], name=op.f('fk_user_entry_progress_entry_id_entries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_entry_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'entry_id', name=op.f('pk_user_entry_progress'))
    )
    op.create_index(op.f('ix_user_entry_progress_entry_id'), 'user_entry_progress', ['entry_id'], unique=False)
    op.create_index('ix_user_entry_progress_user_due', 'user_entry_progress', ['user_id', 'due_at'], unique=False)
    op.add_column('users', sa.Column('mastered_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('custom_mastered_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'custom_mastered_count')
    op.drop_column('users', 'mastered_count')
    op.drop_index('ix_user_entry_progress_user_due', table_name='user_entry_progress')
    op.drop_index(op.f('ix_user_entry_progress_entry_id'), table_name='user_entry_progress')
    op.drop_table('user_entry_progress')
    op.drop_index(op.f('ix_user_course_entries_entry_id'), table_name='user_course_entries')
    op.drop_index(op.f('ix_user_course_entries_course_id'), table_name='user_course_entries')
    op.drop_table('user_course_entries')
    op.drop_index(op.f('ix_study_sessions_user_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_course_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index('ix_review_logs_user_answered', table_name='review_logs')
    op.drop_index(op.f('ix_review_logs_entry_id'), table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_index(op.f('ix_audio_jobs_entry_id'), table_name='audio_jobs')
    op.drop_table('audio_jobs')
    op.drop_index(op.f('ix_user_courses_user_id'), table_name='user_courses')
    op.drop_table('user_courses')
    op.drop_index('uq_entries_owner_headword_lower', table_name='entries', postgresql_where=sa.text("source = 'user'"))
    op.drop_index(op.f('ix_entries_owner_user_id'), table_name='entries')
    op.drop_index('ix_entries_headword_lower', table_name='entries')
    op.drop_table('entries')
    # ### end Alembic commands ###
