"""
Nội dung mục từ MẪU cho lộ trình dev (seeds/seed_dev_roadmap.py): A1 và A2, mỗi chặng 30 mục chia 2 bài × 15.

- Nội dung nháp tự viết (không chép từ điển). Mỗi câu ví dụ chứa ĐÚNG mục từ (để có câu điền vào chỗ trống, mức 4).
- A1: mỗi chặng có 6 mục đã nằm trong seeds/seed_dev_entries.py (dùng lại, đứng đầu bài 1) + 24 mục ở đây.
- A2: 30 mục mỗi chặng, có xen cụm từ: `col` = collocation, `pv` = phrasal verb (trường thứ 6 của bộ).
Bộ: (mục từ, loại từ, phiên âm, nghĩa tiếng Việt, câu ví dụ[, kiểu cụm từ]).
"""

N, V, ADJ, ADV, PREP, INTJ, PV, COL = "danh từ", "động từ", "tính từ", "trạng từ", "giới từ", "thán từ", "cụm động từ", "cụm từ"

# chủ đề → (tên 2 bài, danh sách mục từ)
A1: dict[str, tuple[list[str], list[tuple]]] = {
    "Chào hỏi": (["Lời chào đầu tiên", "Giới thiệu bản thân"], [
        ("please", ADV, "/pliːz/", "làm ơn, xin vui lòng", "Please sit down."),
        ("welcome", INTJ, "/ˈwelkəm/", "chào mừng", "Welcome to our class."),
        ("meet", V, "/miːt/", "gặp", "Nice to meet you."),
        ("nice", ADJ, "/naɪs/", "tốt, dễ chịu", "It is a nice day."),
        ("fine", ADJ, "/faɪn/", "khỏe, ổn", "I am fine, thank you."),
        ("yes", INTJ, "/jes/", "vâng, có", "Yes, I am a student."),
        ("no", INTJ, "/nəʊ/", "không", "No, I am not tired."),
        ("okay", ADJ, "/əʊˈkeɪ/", "ổn, được", "Is everything okay?"),
        ("smile", V, "/smaɪl/", "mỉm cười", "Smile at the camera."),
        ("greet", V, "/ɡriːt/", "chào hỏi", "We greet our teacher every morning."),
        ("introduce", V, "/ˌɪntrəˈdjuːs/", "giới thiệu", "Let me introduce my friend Nam."),
        ("age", N, "/eɪdʒ/", "tuổi", "What is your age?"),
        ("old", ADJ, "/əʊld/", "già, cũ; (bao nhiêu) tuổi", "How old are you?"),
        ("from", PREP, "/frɒm/", "từ, đến từ", "I am from Vietnam."),
        ("country", N, "/ˈkʌntri/", "đất nước", "Vietnam is a beautiful country."),
        ("live", V, "/lɪv/", "sống", "I live in Hanoi."),
        ("student", N, "/ˈstjuːdnt/", "học sinh, sinh viên", "She is a student at this school."),
        ("boy", N, "/bɔɪ/", "cậu bé", "The boy is playing football."),
        ("girl", N, "/ɡɜːl/", "cô bé", "That girl is very kind."),
        ("man", N, "/mæn/", "người đàn ông", "The man is waiting outside."),
        ("woman", N, "/ˈwʊmən/", "người phụ nữ", "The woman sells fruit at the market."),
        ("phone", N, "/fəʊn/", "điện thoại", "Can I have your phone number?"),
        ("email", N, "/ˈiːmeɪl/", "thư điện tử", "Please send me an email."),
        ("address", N, "/əˈdres/", "địa chỉ", "What is your address?"),
    ]),
    "Gia đình": (["Người thân trong nhà", "Ngoại hình và tình thân"], [
        ("parent", N, "/ˈpeərənt/", "bố hoặc mẹ", "Each parent signed the form."),
        ("son", N, "/sʌn/", "con trai", "Their son is five years old."),
        ("daughter", N, "/ˈdɔːtə/", "con gái", "Her daughter likes painting."),
        ("grandmother", N, "/ˈɡrænmʌðə/", "bà", "My grandmother tells funny stories."),
        ("grandfather", N, "/ˈɡrænfɑːðə/", "ông", "My grandfather reads the newspaper."),
        ("aunt", N, "/ɑːnt/", "cô, dì, bác gái", "My aunt lives in Da Nang."),
        ("uncle", N, "/ˈʌŋkl/", "chú, bác, cậu", "My uncle is a doctor."),
        ("cousin", N, "/ˈkʌzn/", "anh chị em họ", "My cousin and I play chess."),
        ("husband", N, "/ˈhʌzbənd/", "chồng", "Her husband cooks dinner every night."),
        ("wife", N, "/waɪf/", "vợ", "His wife is a nurse."),
        ("child", N, "/tʃaɪld/", "đứa trẻ", "Every child needs love."),
        ("twin", N, "/twɪn/", "anh chị em sinh đôi", "Lan has a twin brother."),
        ("young", ADJ, "/jʌŋ/", "trẻ", "My parents are still young."),
        ("tall", ADJ, "/tɔːl/", "cao", "My father is very tall."),
        ("short", ADJ, "/ʃɔːt/", "thấp, ngắn", "My sister has short hair."),
        ("hair", N, "/heə/", "tóc", "She has long black hair."),
        ("eye", N, "/aɪ/", "mắt", "He closed one eye."),
        ("face", N, "/feɪs/", "khuôn mặt", "Wash your face before bed."),
        ("kind", ADJ, "/kaɪnd/", "tốt bụng", "Grandma is kind to everyone."),
        ("visit", V, "/ˈvɪzɪt/", "thăm", "We visit our grandparents on Sundays."),
        ("together", ADV, "/təˈɡeðə/", "cùng nhau", "We eat dinner together."),
        ("birthday", N, "/ˈbɜːθdeɪ/", "sinh nhật", "My birthday is in May."),
        ("photo", N, "/ˈfəʊtəʊ/", "bức ảnh", "This is a photo of my family."),
        ("pet", N, "/pet/", "thú cưng", "Our pet cat is very lazy."),
    ]),
    "Số đếm và thời gian": (["Giờ giấc trong ngày", "Ngày, tháng và năm"], [
        ("day", N, "/deɪ/", "ngày", "Have a nice day!"),
        ("month", N, "/mʌnθ/", "tháng", "Next month we go to Hue."),
        ("year", N, "/jɪə/", "năm", "This year I study English."),
        ("night", N, "/naɪt/", "ban đêm", "I read before I sleep at night."),
        ("evening", N, "/ˈiːvnɪŋ/", "buổi tối", "We watch TV in the evening."),
        ("afternoon", N, "/ˌɑːftəˈnuːn/", "buổi chiều", "I play football in the afternoon."),
        ("tomorrow", ADV, "/təˈmɒrəʊ/", "ngày mai", "See you tomorrow!"),
        ("yesterday", ADV, "/ˈjestədeɪ/", "hôm qua", "It rained yesterday."),
        ("clock", N, "/klɒk/", "đồng hồ (treo tường)", "The clock on the wall is slow."),
        ("time", N, "/taɪm/", "thời gian; giờ", "What time is it?"),
        ("early", ADV, "/ˈɜːli/", "sớm", "I get up early."),
        ("late", ADJ, "/leɪt/", "muộn", "Don't be late for class."),
        ("second", N, "/ˈsekənd/", "giây", "Wait one second, please."),
        ("half", N, "/hɑːf/", "một nửa", "It is half past seven."),
        ("hundred", N, "/ˈhʌndrəd/", "một trăm", "There are a hundred students here."),
        ("first", ADJ, "/fɜːst/", "đầu tiên", "January is the first month."),
        ("last", ADJ, "/lɑːst/", "cuối cùng", "December is the last month."),
        ("Monday", N, "/ˈmʌndeɪ/", "thứ Hai", "School starts on Monday."),
        ("weekend", N, "/ˌwiːkˈend/", "cuối tuần", "We relax at the weekend."),
        ("calendar", N, "/ˈkælɪndə/", "lịch", "Check the calendar for the date."),
        ("date", N, "/deɪt/", "ngày tháng", "What is the date today?"),
        ("always", ADV, "/ˈɔːlweɪz/", "luôn luôn", "I always brush my teeth."),
        ("never", ADV, "/ˈnevə/", "không bao giờ", "He is never late."),
        ("now", ADV, "/naʊ/", "bây giờ", "Let's go now."),
    ]),
    "Đồ ăn": (["Bữa ăn trong ngày", "Đồ uống và hương vị"], [
        ("egg", N, "/eɡ/", "quả trứng", "I eat an egg every morning."),
        ("milk", N, "/mɪlk/", "sữa", "The milk is cold."),
        ("fish", N, "/fɪʃ/", "cá", "We have fish for dinner."),
        ("chicken", N, "/ˈtʃɪkɪn/", "thịt gà; con gà", "Chicken soup is my favourite."),
        ("meat", N, "/miːt/", "thịt", "He does not eat meat."),
        ("noodles", N, "/ˈnuːdlz/", "mì, bún, phở", "I love beef noodles."),
        ("vegetable", N, "/ˈvedʒtəbl/", "rau củ", "Carrot is my favourite vegetable."),
        ("fruit", N, "/fruːt/", "trái cây", "Fruit is good for you."),
        ("banana", N, "/bəˈnɑːnə/", "quả chuối", "The monkey eats a banana."),
        ("orange", N, "/ˈɒrɪndʒ/", "quả cam", "Can I have an orange?"),
        ("tea", N, "/tiː/", "trà", "Grandpa drinks green tea."),
        ("coffee", N, "/ˈkɒfi/", "cà phê", "Vietnamese coffee is strong."),
        ("juice", N, "/dʒuːs/", "nước ép", "I want a glass of juice."),
        ("cake", N, "/keɪk/", "bánh ngọt", "Mum made a chocolate cake."),
        ("sugar", N, "/ˈʃʊɡə/", "đường", "No sugar in my tea, please."),
        ("salt", N, "/sɔːlt/", "muối", "Add a little salt."),
        ("soup", N, "/suːp/", "canh, súp", "The soup is too hot."),
        ("breakfast", N, "/ˈbrekfəst/", "bữa sáng", "I have breakfast at seven."),
        ("lunch", N, "/lʌntʃ/", "bữa trưa", "We eat lunch at school."),
        ("dinner", N, "/ˈdɪnə/", "bữa tối", "Dinner is ready!"),
        ("eat", V, "/iːt/", "ăn", "Let's eat together."),
        ("drink", V, "/drɪŋk/", "uống", "Drink some water."),
        ("delicious", ADJ, "/dɪˈlɪʃəs/", "ngon", "This pho is delicious."),
        ("thirsty", ADJ, "/ˈθɜːsti/", "khát", "I am thirsty after running."),
    ]),
    "Nhà cửa": (["Các phòng trong nhà", "Đồ đạc và việc nhà"], [
        ("bedroom", N, "/ˈbedruːm/", "phòng ngủ", "My bedroom is upstairs."),
        ("bathroom", N, "/ˈbɑːθruːm/", "phòng tắm", "The bathroom is next to the kitchen."),
        ("living room", N, "/ˈlɪvɪŋ ruːm/", "phòng khách", "We watch films in the living room.", "col"),
        ("table", N, "/ˈteɪbl/", "cái bàn", "Put the cups on the table."),
        ("chair", N, "/tʃeə/", "cái ghế", "This chair is comfortable."),
        ("sofa", N, "/ˈsəʊfə/", "ghế sô-pha", "The cat sleeps on the sofa."),
        ("floor", N, "/flɔː/", "sàn nhà; tầng", "Don't sit on the floor."),
        ("wall", N, "/wɔːl/", "bức tường", "We painted the wall blue."),
        ("roof", N, "/ruːf/", "mái nhà", "There is a bird on the roof."),
        ("garden", N, "/ˈɡɑːdn/", "khu vườn", "Grandma grows herbs in the garden."),
        ("stairs", N, "/steəz/", "cầu thang", "Walk up the stairs carefully."),
        ("lamp", N, "/læmp/", "đèn bàn", "Turn on the lamp, please."),
        ("cupboard", N, "/ˈkʌbəd/", "tủ chén, tủ đựng đồ", "The plates are in the cupboard."),
        ("fridge", N, "/frɪdʒ/", "tủ lạnh", "Put the milk in the fridge."),
        ("shower", N, "/ˈʃaʊə/", "vòi sen", "I take a shower every evening."),
        ("key", N, "/kiː/", "chìa khóa", "I can't find my key."),
        ("clean", V, "/kliːn/", "dọn dẹp; sạch", "Please clean your room."),
        ("dirty", ADJ, "/ˈdɜːti/", "bẩn", "Your shoes are dirty."),
        ("big", ADJ, "/bɪɡ/", "to, lớn", "They live in a big house."),
        ("small", ADJ, "/smɔːl/", "nhỏ", "Our flat is small but cosy."),
        ("flat", N, "/flæt/", "căn hộ", "We rent a flat in the city."),
        ("neighbour", N, "/ˈneɪbə/", "hàng xóm", "Our neighbour has a big dog."),
        ("sleep", V, "/sliːp/", "ngủ", "I sleep eight hours a night."),
        ("wash", V, "/wɒʃ/", "rửa, giặt", "Wash your hands before lunch."),
    ]),
    "Đi lại": (["Phương tiện giao thông", "Hỏi và chỉ đường"], [
        ("car", N, "/kɑː/", "ô tô", "My uncle has a red car."),
        ("train", N, "/treɪn/", "tàu hỏa", "The train leaves at nine."),
        ("plane", N, "/pleɪn/", "máy bay", "The plane lands in Da Nang."),
        ("taxi", N, "/ˈtæksi/", "xe taxi", "Let's take a taxi home."),
        ("boat", N, "/bəʊt/", "con thuyền", "We crossed the river by boat."),
        ("motorbike", N, "/ˈməʊtəbaɪk/", "xe máy", "My mother rides a motorbike to work."),
        ("station", N, "/ˈsteɪʃn/", "nhà ga, bến", "Meet me at the station."),
        ("airport", N, "/ˈeəpɔːt/", "sân bay", "Noi Bai airport is very busy."),
        ("road", N, "/rəʊd/", "con đường", "Be careful on the road."),
        ("map", N, "/mæp/", "bản đồ", "Look at the map."),
        ("right", N, "/raɪt/", "bên phải", "Turn right at the corner."),
        ("straight", ADV, "/streɪt/", "thẳng", "Go straight for two minutes."),
        ("stop", N, "/stɒp/", "điểm dừng; dừng lại", "The bus stop is near my house."),
        ("drive", V, "/draɪv/", "lái xe", "Can you drive a car?"),
        ("ride", V, "/raɪd/", "đi (xe đạp, xe máy)", "I ride to school every day."),
        ("fast", ADJ, "/fɑːst/", "nhanh", "This train is very fast."),
        ("slow", ADJ, "/sləʊ/", "chậm", "The old bus is slow."),
        ("near", PREP, "/nɪə/", "gần", "The park is near here."),
        ("far", ADV, "/fɑː/", "xa", "Is the airport far from here?"),
        ("travel", V, "/ˈtrævl/", "đi du lịch, di chuyển", "I love to travel by train."),
        ("go", V, "/ɡəʊ/", "đi", "Where do you go after school?"),
        ("come", V, "/kʌm/", "đến", "Come here, please."),
        ("turn", V, "/tɜːn/", "rẽ", "Don't turn here, go straight on."),
        ("bridge", N, "/brɪdʒ/", "cây cầu", "Long Bien bridge is very old."),
    ]),
    "Mua sắm": (["Ở cửa hàng", "Quần áo và thanh toán"], [
        ("sell", V, "/sel/", "bán", "They sell fresh fruit here."),
        ("pay", V, "/peɪ/", "trả tiền", "Can I pay by card?"),
        ("cost", V, "/kɒst/", "có giá", "How much does it cost?"),
        ("expensive", ADJ, "/ɪkˈspensɪv/", "đắt", "This phone is too expensive."),
        ("bag", N, "/bæɡ/", "cái túi", "I need a new school bag."),
        ("shoes", N, "/ʃuːz/", "đôi giày", "These shoes are very comfortable."),
        ("shirt", N, "/ʃɜːt/", "áo sơ mi", "He wears a white shirt."),
        ("dress", N, "/dres/", "váy liền", "She bought a blue dress."),
        ("size", N, "/saɪz/", "cỡ, kích thước", "What size do you need?"),
        ("colour", N, "/ˈkʌlə/", "màu sắc", "What colour is your bag?"),
        ("card", N, "/kɑːd/", "thẻ", "I lost my bank card."),
        ("cash", N, "/kæʃ/", "tiền mặt", "Do you have cash?"),
        ("sale", N, "/seɪl/", "đợt giảm giá", "The shop has a big sale."),
        ("customer", N, "/ˈkʌstəmə/", "khách hàng", "The customer is always right."),
        ("open", ADJ, "/ˈəʊpən/", "mở cửa", "The bakery is open until nine."),
        ("closed", ADJ, "/kləʊzd/", "đóng cửa", "Sorry, we are closed."),
        ("want", V, "/wɒnt/", "muốn", "I want this one."),
        ("need", V, "/niːd/", "cần", "Do you need a bag?"),
        ("try on", PV, "/traɪ ɒn/", "mặc thử", "Can I try on this jacket?", "pv"),
        ("basket", N, "/ˈbɑːskɪt/", "cái giỏ", "Put the apples in the basket."),
        ("supermarket", N, "/ˈsuːpəmɑːkɪt/", "siêu thị", "We shop at the supermarket on Saturday."),
        ("gift", N, "/ɡɪft/", "món quà", "This is a gift for you."),
        ("clothes", N, "/kləʊðz/", "quần áo", "I need new clothes."),
        ("how much", COL, "/haʊ mʌtʃ/", "bao nhiêu (tiền)", "How much is this hat?", "col"),
    ]),
    "Thời tiết": (["Trời hôm nay thế nào?", "Bốn mùa"], [
        ("weather", N, "/ˈweðə/", "thời tiết", "The weather is nice today."),
        ("snow", N, "/snəʊ/", "tuyết", "Children love the snow."),
        ("storm", N, "/stɔːm/", "cơn bão", "A big storm is coming."),
        ("sunny", ADJ, "/ˈsʌni/", "nắng", "It is sunny this morning."),
        ("rainy", ADJ, "/ˈreɪni/", "có mưa", "I stay home on rainy days."),
        ("cloudy", ADJ, "/ˈklaʊdi/", "nhiều mây", "The sky is cloudy."),
        ("windy", ADJ, "/ˈwɪndi/", "có gió", "It is windy by the sea."),
        ("warm", ADJ, "/wɔːm/", "ấm", "Spring is warm."),
        ("cool", ADJ, "/kuːl/", "mát", "The evening is cool."),
        ("wet", ADJ, "/wet/", "ướt", "My shoes are wet."),
        ("dry", ADJ, "/draɪ/", "khô", "The air is dry in winter."),
        ("umbrella", N, "/ʌmˈbrelə/", "cái ô", "Take an umbrella with you."),
        ("coat", N, "/kəʊt/", "áo khoác", "Wear a coat, it is cold."),
        ("temperature", N, "/ˈtemprətʃə/", "nhiệt độ", "The temperature is thirty degrees."),
        ("season", N, "/ˈsiːzn/", "mùa", "Which season do you like?"),
        ("summer", N, "/ˈsʌmə/", "mùa hè", "We go to the beach in summer."),
        ("winter", N, "/ˈwɪntə/", "mùa đông", "Winter in Sa Pa is very cold."),
        ("spring", N, "/sprɪŋ/", "mùa xuân", "Flowers open in spring."),
        ("autumn", N, "/ˈɔːtəm/", "mùa thu", "Hanoi is beautiful in autumn."),
        ("sky", N, "/skaɪ/", "bầu trời", "The sky is blue."),
        ("rainbow", N, "/ˈreɪnbəʊ/", "cầu vồng", "Look, a rainbow!"),
        ("fog", N, "/fɒɡ/", "sương mù", "There is thick fog on the mountain."),
        ("ice", N, "/aɪs/", "băng, đá", "Put some ice in my drink."),
        ("degree", N, "/dɪˈɡriː/", "độ", "It is one degree below zero."),
    ]),
    "Thiên nhiên": (["Núi, sông và rừng", "Muông thú quanh ta"], [
        ("forest", N, "/ˈfɒrɪst/", "khu rừng", "Many animals live in the forest."),
        ("lake", N, "/leɪk/", "cái hồ", "We walk around the lake."),
        ("beach", N, "/biːtʃ/", "bãi biển", "The beach is very clean."),
        ("island", N, "/ˈaɪlənd/", "hòn đảo", "Phu Quoc is a big island."),
        ("hill", N, "/hɪl/", "ngọn đồi", "The house is on a hill."),
        ("grass", N, "/ɡrɑːs/", "cỏ", "The cows eat grass."),
        ("leaf", N, "/liːf/", "chiếc lá", "A yellow leaf fell on my head."),
        ("rock", N, "/rɒk/", "tảng đá", "The boy sits on a big rock."),
        ("bird", N, "/bɜːd/", "con chim", "The bird can fly high."),
        ("cat", N, "/kæt/", "con mèo", "Our cat sleeps all day."),
        ("cow", N, "/kaʊ/", "con bò", "The cow gives us milk."),
        ("horse", N, "/hɔːs/", "con ngựa", "She can ride a horse."),
        ("duck", N, "/dʌk/", "con vịt", "A duck is swimming in the pond."),
        ("butterfly", N, "/ˈbʌtəflaɪ/", "con bướm", "A butterfly landed on the flower."),
        ("sand", N, "/sænd/", "cát", "The children play in the sand."),
        ("star", N, "/stɑː/", "ngôi sao", "I can see a bright star."),
        ("moon", N, "/muːn/", "mặt trăng", "The moon is full tonight."),
        ("plant", N, "/plɑːnt/", "cây (nhỏ); trồng", "Water the plant every day."),
        ("field", N, "/fiːld/", "cánh đồng", "Farmers work in the field."),
        ("cave", N, "/keɪv/", "hang động", "The cave is dark and cool."),
        ("dog", N, "/dɒɡ/", "con chó", "The dog runs in the park."),
        ("fly", V, "/flaɪ/", "bay", "Birds fly south in winter."),
        ("swim", V, "/swɪm/", "bơi", "Fish swim in the river."),
        ("green", ADJ, "/ɡriːn/", "màu xanh lá", "The rice fields are green."),
    ]),
    "Trường học và học tập": (["Lớp học của em", "Môn học và bài tập"], [
        ("class", N, "/klɑːs/", "lớp học", "Our class has thirty students."),
        ("classroom", N, "/ˈklɑːsruːm/", "phòng học", "The classroom is on the second floor."),
        ("desk", N, "/desk/", "bàn học", "Keep your desk tidy."),
        ("pencil", N, "/ˈpensl/", "bút chì", "Write your name in pencil."),
        ("ruler", N, "/ˈruːlə/", "thước kẻ", "Draw a line with a ruler."),
        ("lesson", N, "/ˈlesn/", "bài học", "Today's lesson is about animals."),
        ("test", N, "/test/", "bài kiểm tra", "We have a test on Friday."),
        ("question", N, "/ˈkwestʃən/", "câu hỏi", "Can I ask a question?"),
        ("answer", N, "/ˈɑːnsə/", "câu trả lời", "Write the answer on the board."),
        ("read", V, "/riːd/", "đọc", "I read a story every night."),
        ("write", V, "/raɪt/", "viết", "Write a short email to your friend."),
        ("listen", V, "/ˈlɪsn/", "nghe", "Listen to the teacher."),
        ("speak", V, "/spiːk/", "nói", "Can you speak English?"),
        ("study", V, "/ˈstʌdi/", "học, nghiên cứu", "I study at the library."),
        ("subject", N, "/ˈsʌbdʒɪkt/", "môn học", "Maths is my favourite subject."),
        ("maths", N, "/mæθs/", "môn toán", "Maths is hard but fun."),
        ("English", N, "/ˈɪŋɡlɪʃ/", "tiếng Anh", "I practise English every day."),
        ("music", N, "/ˈmjuːzɪk/", "âm nhạc", "We have music on Tuesday."),
        ("ask", V, "/ɑːsk/", "hỏi", "Ask your teacher for help."),
        ("word", N, "/wɜːd/", "từ", "Learn one new word a day."),
        ("page", N, "/peɪdʒ/", "trang", "Open your book to page ten."),
        ("board", N, "/bɔːd/", "cái bảng", "The teacher writes on the board."),
        ("notebook", N, "/ˈnəʊtbʊk/", "quyển vở", "Copy the words into your notebook."),
        ("easy", ADJ, "/ˈiːzi/", "dễ", "This exercise is easy."),
    ]),
}

A2: dict[str, tuple[list[str], list[tuple]]] = {
    "Công việc hằng ngày": (["Buổi sáng bận rộn", "Ở nhà và nơi làm việc"], [
        ("get up", PV, "/ɡet ʌp/", "thức dậy, ra khỏi giường", "I usually get up at six.", "pv"),
        ("wake up", PV, "/weɪk ʌp/", "tỉnh giấc", "I wake up before my alarm.", "pv"),
        ("alarm", N, "/əˈlɑːm/", "chuông báo thức", "My alarm rings at six."),
        ("get dressed", COL, "/ɡet drest/", "mặc quần áo", "Get dressed quickly, we are late.", "col"),
        ("make the bed", COL, "/meɪk ðə bed/", "dọn giường", "I make the bed every morning.", "col"),
        ("do the housework", COL, "/duː ðə ˈhaʊswɜːk/", "làm việc nhà", "We do the housework on Sundays.", "col"),
        ("go to work", COL, "/ɡəʊ tə wɜːk/", "đi làm", "Most people go to work by motorbike.", "col"),
        ("commute", V, "/kəˈmjuːt/", "đi lại giữa nhà và nơi làm", "I commute by bus every day."),
        ("routine", N, "/ruːˈtiːn/", "thói quen hằng ngày", "Exercise is part of my routine."),
        ("usually", ADV, "/ˈjuːʒuəli/", "thường thường", "I usually walk to school."),
        ("sometimes", ADV, "/ˈsʌmtaɪmz/", "thỉnh thoảng", "Sometimes I cook dinner."),
        ("rarely", ADV, "/ˈreəli/", "hiếm khi", "She rarely drinks coffee."),
        ("busy", ADJ, "/ˈbɪzi/", "bận rộn", "Mondays are always busy."),
        ("break", N, "/breɪk/", "giờ nghỉ", "We have a short break at ten."),
        ("schedule", N, "/ˈʃedjuːl/", "lịch trình", "My schedule is full this week."),
        ("take a nap", COL, "/teɪk ə næp/", "chợp mắt", "Grandpa likes to take a nap after lunch.", "col"),
        ("go to bed", COL, "/ɡəʊ tə bed/", "đi ngủ", "I go to bed at eleven.", "col"),
        ("stay up", PV, "/steɪ ʌp/", "thức khuya", "Don't stay up too late.", "pv"),
        ("do homework", COL, "/duː ˈhəʊmwɜːk/", "làm bài tập về nhà", "I do homework after dinner.", "col"),
        ("iron", V, "/ˈaɪən/", "là, ủi (quần áo)", "I iron my shirt every Monday."),
        ("tidy", V, "/ˈtaɪdi/", "dọn gọn gàng", "Please tidy your desk."),
        ("feed", V, "/fiːd/", "cho ăn", "I feed the cat every morning."),
        ("water the plants", COL, "/ˈwɔːtə ðə plɑːnts/", "tưới cây", "Grandma asked me to water the plants.", "col"),
        ("take out the rubbish", COL, "/teɪk aʊt ðə ˈrʌbɪʃ/", "đổ rác", "Please take out the rubbish tonight.", "col"),
        ("hurry", V, "/ˈhʌri/", "vội vàng", "Hurry, the bus is coming!"),
        ("on time", COL, "/ɒn taɪm/", "đúng giờ", "The train arrived on time.", "col"),
        ("office", N, "/ˈɒfɪs/", "văn phòng", "Her office is on the tenth floor."),
        ("colleague", N, "/ˈkɒliːɡ/", "đồng nghiệp", "My colleague helps me a lot."),
        ("meeting", N, "/ˈmiːtɪŋ/", "cuộc họp", "The meeting starts at nine."),
        ("finish", V, "/ˈfɪnɪʃ/", "hoàn thành, kết thúc", "I finish work at five."),
    ]),
    "Cảm xúc": (["Vui, buồn, giận, sợ", "Nói về cảm xúc"], [
        ("happy", ADJ, "/ˈhæpi/", "vui vẻ", "I am happy to see you."),
        ("sad", ADJ, "/sæd/", "buồn", "The film made me sad."),
        ("angry", ADJ, "/ˈæŋɡri/", "tức giận", "Dad was angry about the mess."),
        ("afraid", ADJ, "/əˈfreɪd/", "sợ", "My sister is afraid of dogs."),
        ("tired", ADJ, "/ˈtaɪəd/", "mệt", "I feel tired after work."),
        ("excited", ADJ, "/ɪkˈsaɪtɪd/", "hào hứng", "We are excited about the trip."),
        ("bored", ADJ, "/bɔːd/", "chán", "I am bored at home."),
        ("worried", ADJ, "/ˈwʌrid/", "lo lắng", "Mum is worried about the test."),
        ("nervous", ADJ, "/ˈnɜːvəs/", "hồi hộp, căng thẳng", "I feel nervous before exams."),
        ("surprised", ADJ, "/səˈpraɪzd/", "ngạc nhiên", "She was surprised by the gift."),
        ("proud", ADJ, "/praʊd/", "tự hào", "My parents are proud of me."),
        ("lonely", ADJ, "/ˈləʊnli/", "cô đơn", "He feels lonely in the new city."),
        ("calm", ADJ, "/kɑːm/", "bình tĩnh", "Stay calm and breathe."),
        ("upset", ADJ, "/ʌpˈset/", "buồn bực", "She was upset about the news."),
        ("embarrassed", ADJ, "/ɪmˈbærəst/", "ngượng ngùng", "I felt embarrassed when I fell."),
        ("relaxed", ADJ, "/rɪˈlækst/", "thư thái", "I feel relaxed on holiday."),
        ("jealous", ADJ, "/ˈdʒeləs/", "ghen tị", "He is jealous of his brother."),
        ("scared", ADJ, "/skeəd/", "sợ hãi", "The little boy was scared of the dark."),
        ("cheerful", ADJ, "/ˈtʃɪəfl/", "vui tươi", "Our teacher is always cheerful."),
        ("feeling", N, "/ˈfiːlɪŋ/", "cảm giác, cảm xúc", "I have a good feeling about this."),
        ("cry", V, "/kraɪ/", "khóc", "Babies cry when they are hungry."),
        ("laugh", V, "/lɑːf/", "cười thành tiếng", "His jokes make me laugh."),
        ("miss", V, "/mɪs/", "nhớ (ai đó)", "I miss my grandparents."),
        ("hope", V, "/həʊp/", "hy vọng", "I hope you feel better."),
        ("cheer up", PV, "/tʃɪər ʌp/", "vui lên", "Cheer up, it is not so bad!", "pv"),
        ("calm down", PV, "/kɑːm daʊn/", "bình tĩnh lại", "Please calm down and listen.", "pv"),
        ("be fond of", COL, "/bi fɒnd əv/", "thích, quý mến", "I will always be fond of this town.", "col"),
        ("in a good mood", COL, "/ɪn ə ɡʊd muːd/", "tâm trạng tốt", "She is in a good mood today.", "col"),
        ("stressed", ADJ, "/strest/", "căng thẳng", "Students feel stressed in exam week."),
        ("grateful", ADJ, "/ˈɡreɪtfl/", "biết ơn", "I am grateful for your help."),
    ]),
    "Lễ hội": (["Tết và Trung thu", "Tiệc tùng và truyền thống"], [
        ("festival", N, "/ˈfestɪvl/", "lễ hội", "The lantern festival is in Hoi An."),
        ("lantern", N, "/ˈlæntən/", "đèn lồng", "Each child carries a lantern."),
        ("celebrate", V, "/ˈselɪbreɪt/", "ăn mừng, tổ chức", "We celebrate Tet with our family."),
        ("Lunar New Year", N, "/ˈluːnə njuː jɪə/", "Tết Nguyên Đán", "Lunar New Year is the biggest holiday in Vietnam.", "col"),
        ("lucky money", N, "/ˈlʌki ˈmʌni/", "tiền lì xì", "Children get lucky money at Tet.", "col"),
        ("fireworks", N, "/ˈfaɪəwɜːks/", "pháo hoa", "We watched the fireworks at midnight."),
        ("parade", N, "/pəˈreɪd/", "cuộc diễu hành", "The parade passes through the old town."),
        ("costume", N, "/ˈkɒstjuːm/", "trang phục hóa trang", "She wore a dragon costume."),
        ("tradition", N, "/trəˈdɪʃn/", "truyền thống", "Giving gifts is an old tradition."),
        ("traditional", ADJ, "/trəˈdɪʃənl/", "(thuộc) truyền thống", "Ao dai is traditional clothing."),
        ("decorate", V, "/ˈdekəreɪt/", "trang trí", "We decorate the house with flowers."),
        ("invite", V, "/ɪnˈvaɪt/", "mời", "I want to invite you to my party."),
        ("party", N, "/ˈpɑːti/", "bữa tiệc", "The party starts at seven."),
        ("guest", N, "/ɡest/", "khách", "Every guest brought a small gift."),
        ("wish", N, "/wɪʃ/", "điều ước, lời chúc", "Make a wish and blow out the candles."),
        ("candle", N, "/ˈkændl/", "cây nến", "Light a candle on the cake."),
        ("dragon dance", N, "/ˈdræɡən dɑːns/", "múa lân, múa rồng", "The dragon dance is very loud.", "col"),
        ("mooncake", N, "/ˈmuːnkeɪk/", "bánh trung thu", "Grandma bought a mooncake for me."),
        ("holiday", N, "/ˈhɒlədeɪ/", "ngày lễ, kỳ nghỉ", "Monday is a public holiday."),
        ("ceremony", N, "/ˈserəməni/", "nghi lễ", "The opening ceremony was beautiful."),
        ("crowd", N, "/kraʊd/", "đám đông", "A big crowd watched the show."),
        ("drum", N, "/drʌm/", "cái trống", "He plays the drum in the parade."),
        ("temple", N, "/ˈtempl/", "ngôi đền", "Many people visit the temple at Tet."),
        ("pray", V, "/preɪ/", "cầu nguyện", "People pray for good luck."),
        ("luck", N, "/lʌk/", "sự may mắn", "Red is the colour of luck."),
        ("get together", PV, "/ɡet təˈɡeðə/", "tụ họp", "Families get together at Tet.", "pv"),
        ("dress up", PV, "/dres ʌp/", "ăn diện, hóa trang", "Kids dress up for Halloween.", "pv"),
        ("take part in", COL, "/teɪk pɑːt ɪn/", "tham gia", "Thousands take part in the festival.", "col"),
        ("gather", V, "/ˈɡæðə/", "tụ tập", "People gather by the river."),
        ("present", N, "/ˈpreznt/", "món quà", "Thank you for the lovely present."),
    ]),
    "Thành phố": (["Đường phố và giao thông", "Những nơi trong thành phố"], [
        ("city", N, "/ˈsɪti/", "thành phố", "Da Nang is a modern city."),
        ("town", N, "/taʊn/", "thị trấn", "I grew up in a small town."),
        ("building", N, "/ˈbɪldɪŋ/", "tòa nhà", "That building has forty floors."),
        ("traffic", N, "/ˈtræfɪk/", "giao thông", "The traffic is terrible today."),
        ("rush hour", N, "/rʌʃ aʊə/", "giờ cao điểm", "Avoid the bridge at rush hour.", "col"),
        ("traffic jam", N, "/ˈtræfɪk dʒæm/", "tắc đường", "We were stuck in a traffic jam.", "col"),
        ("crossroads", N, "/ˈkrɒsrəʊdz/", "ngã tư", "Turn left at the crossroads."),
        ("traffic light", N, "/ˈtræfɪk laɪt/", "đèn giao thông", "Stop at the red traffic light.", "col"),
        ("pavement", N, "/ˈpeɪvmənt/", "vỉa hè", "Don't park on the pavement."),
        ("square", N, "/skweə/", "quảng trường", "There is a concert in the square."),
        ("museum", N, "/mjuˈziːəm/", "bảo tàng", "The museum opens at eight."),
        ("hospital", N, "/ˈhɒspɪtl/", "bệnh viện", "The hospital is next to the park."),
        ("bank", N, "/bæŋk/", "ngân hàng", "I need to go to the bank."),
        ("post office", N, "/pəʊst ˈɒfɪs/", "bưu điện", "The post office is closed on Sunday.", "col"),
        ("park", N, "/pɑːk/", "công viên", "We jog in the park."),
        ("restaurant", N, "/ˈrestrɒnt/", "nhà hàng", "This restaurant serves seafood."),
        ("cinema", N, "/ˈsɪnəmə/", "rạp chiếu phim", "Let's go to the cinema tonight."),
        ("library", N, "/ˈlaɪbrəri/", "thư viện", "The library is very quiet."),
        ("crowded", ADJ, "/ˈkraʊdɪd/", "đông đúc", "The market is crowded on weekends."),
        ("noisy", ADJ, "/ˈnɔɪzi/", "ồn ào", "The street is noisy at night."),
        ("quiet", ADJ, "/ˈkwaɪət/", "yên tĩnh", "Our street is quiet."),
        ("modern", ADJ, "/ˈmɒdn/", "hiện đại", "The new airport is very modern."),
        ("downtown", ADV, "/ˌdaʊnˈtaʊn/", "ở trung tâm thành phố", "We live downtown."),
        ("neighbourhood", N, "/ˈneɪbəhʊd/", "khu phố", "My neighbourhood is friendly."),
        ("corner", N, "/ˈkɔːnə/", "góc đường", "The café is on the corner."),
        ("get lost", COL, "/ɡet lɒst/", "bị lạc", "Tourists often get lost in the old quarter.", "col"),
        ("get on", PV, "/ɡet ɒn/", "lên (xe)", "Get on the bus here.", "pv"),
        ("get off", PV, "/ɡet ɒf/", "xuống (xe)", "Get off at the next stop.", "pv"),
        ("population", N, "/ˌpɒpjuˈleɪʃn/", "dân số", "The population of the city is growing."),
        ("underground", N, "/ˈʌndəɡraʊnd/", "tàu điện ngầm", "Hanoi is building an underground."),
    ]),
    "Khám phá": (["Lên đường phiêu lưu", "Hang động và rừng sâu"], [
        ("explore", V, "/ɪkˈsplɔː/", "khám phá", "We want to explore the caves of Phong Nha."),
        ("adventure", N, "/ədˈventʃə/", "cuộc phiêu lưu", "Our trip was a real adventure."),
        ("journey", N, "/ˈdʒɜːni/", "hành trình", "The journey takes six hours."),
        ("guide", N, "/ɡaɪd/", "hướng dẫn viên", "Our guide speaks good English."),
        ("tourist", N, "/ˈtʊərɪst/", "khách du lịch", "Every tourist wants a photo here."),
        ("backpack", N, "/ˈbækpæk/", "ba lô", "Pack your backpack the night before."),
        ("camp", V, "/kæmp/", "cắm trại", "We camp by the lake."),
        ("tent", N, "/tent/", "cái lều", "Put up the tent before dark."),
        ("torch", N, "/tɔːtʃ/", "đèn pin", "Bring a torch for the cave."),
        ("climb", V, "/klaɪm/", "leo", "It took us three hours to climb the hill."),
        ("trip", N, "/trɪp/", "chuyến đi", "How was your trip?"),
        ("discover", V, "/dɪˈskʌvə/", "phát hiện", "Scientists discover new species every year."),
        ("jungle", N, "/ˈdʒʌŋɡl/", "rừng rậm", "Monkeys live in the jungle."),
        ("path", N, "/pɑːθ/", "lối mòn", "Follow the path to the waterfall."),
        ("waterfall", N, "/ˈwɔːtəfɔːl/", "thác nước", "The waterfall is twenty metres high."),
        ("compass", N, "/ˈkʌmpəs/", "la bàn", "Use a compass to find north."),
        ("wild", ADJ, "/waɪld/", "hoang dã", "Wild elephants live in this park."),
        ("dangerous", ADJ, "/ˈdeɪndʒərəs/", "nguy hiểm", "Swimming here is dangerous."),
        ("safe", ADJ, "/seɪf/", "an toàn", "Is this water safe to drink?"),
        ("view", N, "/vjuː/", "quang cảnh", "The view from the top is amazing."),
        ("take photos", COL, "/teɪk ˈfəʊtəʊz/", "chụp ảnh", "Visitors love to take photos of the bridge.", "col"),
        ("set off", PV, "/set ɒf/", "khởi hành", "We set off at dawn.", "pv"),
        ("look around", PV, "/lʊk əˈraʊnd/", "đi xem quanh", "Let's look around the village.", "pv"),
        ("find out", PV, "/faɪnd aʊt/", "tìm hiểu, phát hiện ra", "I want to find out more about this place.", "pv"),
        ("souvenir", N, "/ˌsuːvəˈnɪə/", "quà lưu niệm", "I bought a souvenir for my mum."),
        ("sightseeing", N, "/ˈsaɪtsiːɪŋ/", "việc tham quan", "We went sightseeing in Hue."),
        ("local", ADJ, "/ˈləʊkl/", "(thuộc) địa phương", "Try the local food."),
        ("equipment", N, "/ɪˈkwɪpmənt/", "trang thiết bị", "Check your equipment before the climb."),
        ("boots", N, "/buːts/", "giày bốt", "Wear strong boots for the trail."),
        ("hiking", N, "/ˈhaɪkɪŋ/", "đi bộ đường dài", "Hiking is popular in Sa Pa."),
    ]),
    "Biển và kỳ nghỉ": (["Một ngày ở biển", "Khách sạn và hành lý"], [
        ("coast", N, "/kəʊst/", "bờ biển", "Mui Ne is on the south coast."),
        ("wave", N, "/weɪv/", "con sóng", "A big wave hit the boat."),
        ("shell", N, "/ʃel/", "vỏ sò", "She found a pink shell."),
        ("sunscreen", N, "/ˈsʌnskriːn/", "kem chống nắng", "Put on sunscreen before you go out."),
        ("sunglasses", N, "/ˈsʌnɡlɑːsɪz/", "kính râm", "I forgot my sunglasses."),
        ("swimsuit", N, "/ˈswɪmsuːt/", "đồ bơi", "Don't forget your swimsuit."),
        ("towel", N, "/ˈtaʊəl/", "khăn tắm", "Can I borrow a towel?"),
        ("hotel", N, "/həʊˈtel/", "khách sạn", "Our hotel faces the sea."),
        ("resort", N, "/rɪˈzɔːt/", "khu nghỉ dưỡng", "The resort has three pools."),
        ("book a room", COL, "/bʊk ə ruːm/", "đặt phòng", "I want to book a room for two nights.", "col"),
        ("check in", PV, "/tʃek ɪn/", "nhận phòng, làm thủ tục", "We can check in after two o'clock.", "pv"),
        ("check out", PV, "/tʃek aʊt/", "trả phòng", "Guests must check out by noon.", "pv"),
        ("relax", V, "/rɪˈlæks/", "thư giãn", "I just want to relax on the beach."),
        ("sunbathe", V, "/ˈsʌnbeɪð/", "tắm nắng", "Tourists sunbathe all afternoon."),
        ("dive", V, "/daɪv/", "lặn", "You can dive near the island."),
        ("surf", V, "/sɜːf/", "lướt sóng", "He learned to surf in Da Nang."),
        ("seafood", N, "/ˈsiːfuːd/", "hải sản", "The seafood here is very fresh."),
        ("crab", N, "/kræb/", "con cua", "A small crab ran across the sand."),
        ("sandcastle", N, "/ˈsændkɑːsl/", "lâu đài cát", "The kids built a sandcastle."),
        ("lifeguard", N, "/ˈlaɪfɡɑːd/", "nhân viên cứu hộ", "Swim near the lifeguard."),
        ("sunset", N, "/ˈsʌnset/", "hoàng hôn", "The sunset over the sea is amazing."),
        ("sunrise", N, "/ˈsʌnraɪz/", "bình minh", "We got up early to see the sunrise."),
        ("go on holiday", COL, "/ɡəʊ ɒn ˈhɒlədeɪ/", "đi nghỉ", "We go on holiday every summer.", "col"),
        ("pack", V, "/pæk/", "đóng gói hành lý", "Did you pack the sunscreen?"),
        ("suitcase", N, "/ˈsuːtkeɪs/", "va li", "My suitcase is too heavy."),
        ("passport", N, "/ˈpɑːspɔːt/", "hộ chiếu", "Show your passport at the desk."),
        ("luggage", N, "/ˈlʌɡɪdʒ/", "hành lý", "Leave your luggage at reception."),
        ("reception", N, "/rɪˈsepʃn/", "quầy lễ tân", "Ask at reception for a map."),
        ("swimming pool", N, "/ˈswɪmɪŋ puːl/", "bể bơi", "The swimming pool is open until ten.", "col"),
        ("sunburn", N, "/ˈsʌnbɜːn/", "cháy nắng", "Use cream to avoid sunburn."),
    ]),
    "Thời gian rảnh": (["Sở thích của em", "Thể thao và câu lạc bộ"], [
        ("hobby", N, "/ˈhɒbi/", "sở thích", "My hobby is painting."),
        ("free time", COL, "/friː taɪm/", "thời gian rảnh", "What do you do in your free time?", "col"),
        ("play the guitar", COL, "/pleɪ ðə ɡɪˈtɑː/", "chơi ghi-ta", "My brother can play the guitar.", "col"),
        ("paint", V, "/peɪnt/", "vẽ (bằng màu)", "I like to paint landscapes."),
        ("draw", V, "/drɔː/", "vẽ", "Can you draw a cat?"),
        ("dance", V, "/dɑːns/", "nhảy múa", "Let's dance!"),
        ("sing", V, "/sɪŋ/", "hát", "She loves to sing karaoke."),
        ("chess", N, "/tʃes/", "cờ vua", "Grandpa taught me chess."),
        ("collect", V, "/kəˈlekt/", "sưu tầm", "I collect old stamps."),
        ("watch TV", COL, "/wɒtʃ ˌtiːˈviː/", "xem ti vi", "We watch TV after dinner.", "col"),
        ("go shopping", COL, "/ɡəʊ ˈʃɒpɪŋ/", "đi mua sắm", "Let's go shopping on Saturday.", "col"),
        ("go fishing", COL, "/ɡəʊ ˈfɪʃɪŋ/", "đi câu cá", "My uncle likes to go fishing.", "col"),
        ("cycling", N, "/ˈsaɪklɪŋ/", "đạp xe", "Cycling around the lake is fun."),
        ("photography", N, "/fəˈtɒɡrəfi/", "nhiếp ảnh", "She is interested in photography."),
        ("film", N, "/fɪlm/", "bộ phim", "That film was really funny."),
        ("concert", N, "/ˈkɒnsət/", "buổi hòa nhạc", "We went to a rock concert."),
        ("gym", N, "/dʒɪm/", "phòng tập thể dục", "I go to the gym three times a week."),
        ("jog", V, "/dʒɒɡ/", "chạy bộ", "I jog every morning."),
        ("sport", N, "/spɔːt/", "môn thể thao", "Football is my favourite sport."),
        ("team", N, "/tiːm/", "đội", "Our team won the match."),
        ("join", V, "/dʒɔɪn/", "tham gia", "Do you want to join our club?"),
        ("club", N, "/klʌb/", "câu lạc bộ", "The chess club meets on Fridays."),
        ("member", N, "/ˈmembə/", "thành viên", "Every member pays a small fee."),
        ("hang out", PV, "/hæŋ aʊt/", "đi chơi", "We hang out at the coffee shop.", "pv"),
        ("take up", PV, "/teɪk ʌp/", "bắt đầu (một sở thích)", "I want to take up yoga.", "pv"),
        ("look forward to", PV, "/lʊk ˈfɔːwəd tə/", "mong chờ", "I look forward to the holiday.", "pv"),
        ("spend time", COL, "/spend taɪm/", "dành thời gian", "I spend time with my family at weekends.", "col"),
        ("fan", N, "/fæn/", "người hâm mộ", "He is a big fan of this band."),
        ("favourite", ADJ, "/ˈfeɪvərɪt/", "yêu thích nhất", "What is your favourite game?"),
        ("board game", N, "/bɔːd ɡeɪm/", "trò chơi cờ bàn", "We played a board game all evening.", "col"),
    ]),
    "Tiền và giá cả": (["Ví tiền của em", "Chi tiêu thông minh"], [
        ("coin", N, "/kɔɪn/", "đồng xu", "I found a coin on the floor."),
        ("banknote", N, "/ˈbæŋknəʊt/", "tờ tiền", "This banknote is very old."),
        ("wallet", N, "/ˈwɒlɪt/", "ví (nam)", "I left my wallet at home."),
        ("purse", N, "/pɜːs/", "ví (nữ)", "Her purse is red."),
        ("save", V, "/seɪv/", "tiết kiệm", "I save money for a new bike."),
        ("spend", V, "/spend/", "tiêu (tiền)", "Don't spend all your money."),
        ("borrow", V, "/ˈbɒrəʊ/", "mượn", "Can I borrow ten thousand dong?"),
        ("lend", V, "/lend/", "cho mượn", "Could you lend me your pen?"),
        ("owe", V, "/əʊ/", "nợ", "I owe you a coffee."),
        ("discount", N, "/ˈdɪskaʊnt/", "sự giảm giá", "Students get a discount."),
        ("bill", N, "/bɪl/", "hóa đơn", "Can we have the bill, please?"),
        ("receipt", N, "/rɪˈsiːt/", "biên lai", "Keep the receipt."),
        ("change", N, "/tʃeɪndʒ/", "tiền thối lại", "Here is your change."),
        ("afford", V, "/əˈfɔːd/", "đủ khả năng chi trả", "I can't afford a new laptop."),
        ("budget", N, "/ˈbʌdʒɪt/", "ngân sách", "Our travel budget is small."),
        ("salary", N, "/ˈsæləri/", "tiền lương", "Her salary is paid monthly."),
        ("earn", V, "/ɜːn/", "kiếm (tiền)", "He wants to earn more money."),
        ("rich", ADJ, "/rɪtʃ/", "giàu", "The rich man gave money to the school."),
        ("poor", ADJ, "/pɔː/", "nghèo", "The family was poor but happy."),
        ("price tag", N, "/praɪs tæɡ/", "nhãn giá", "Check the price tag first.", "col"),
        ("bargain", N, "/ˈbɑːɡən/", "món hời", "This jacket was a bargain."),
        ("credit card", N, "/ˈkredɪt kɑːd/", "thẻ tín dụng", "Do you accept credit card payments?", "col"),
        ("cash machine", N, "/kæʃ məˈʃiːn/", "máy rút tiền", "Is there a cash machine near here?", "col"),
        ("withdraw", V, "/wɪðˈdrɔː/", "rút (tiền)", "I need to withdraw some money."),
        ("worth", ADJ, "/wɜːθ/", "đáng giá", "This painting is worth a lot."),
        ("waste money", COL, "/weɪst ˈmʌni/", "phí tiền", "Don't waste money on snacks.", "col"),
        ("pay back", PV, "/peɪ bæk/", "trả lại (tiền)", "I will pay back the money tomorrow.", "pv"),
        ("run out of", PV, "/rʌn aʊt əv/", "hết, cạn", "We run out of milk every Friday.", "pv"),
        ("total", N, "/ˈtəʊtl/", "tổng cộng", "The total is two hundred thousand."),
        ("pocket money", N, "/ˈpɒkɪt ˈmʌni/", "tiền tiêu vặt", "I get pocket money every week.", "col"),
    ]),
    "Kiến trúc": (["Công trình nổi tiếng", "Vật liệu và chi tiết"], [
        ("church", N, "/tʃɜːtʃ/", "nhà thờ", "The church was built in 1880."),
        ("cathedral", N, "/kəˈθiːdrəl/", "nhà thờ lớn", "The cathedral is in District 1."),
        ("tower", N, "/ˈtaʊə/", "tòa tháp", "The bell tower is forty metres tall."),
        ("palace", N, "/ˈpæləs/", "cung điện", "The king lived in this palace."),
        ("gate", N, "/ɡeɪt/", "cổng", "Meet me at the main gate."),
        ("statue", N, "/ˈstætʃuː/", "bức tượng", "There is a statue in the park."),
        ("monument", N, "/ˈmɒnjumənt/", "đài tưởng niệm", "The monument honours the heroes."),
        ("dome", N, "/dəʊm/", "mái vòm", "The dome is covered in gold."),
        ("arch", N, "/ɑːtʃ/", "vòm cổng", "Walk through the stone arch."),
        ("column", N, "/ˈkɒləm/", "cột", "Each column is made of marble."),
        ("brick", N, "/brɪk/", "gạch", "The walls are made of red brick."),
        ("stone", N, "/stəʊn/", "đá", "The old wall is made of stone."),
        ("wood", N, "/wʊd/", "gỗ", "The pagoda is made of wood."),
        ("glass", N, "/ɡlɑːs/", "kính", "The roof is made of glass."),
        ("steel", N, "/stiːl/", "thép", "The tower has a steel frame."),
        ("design", N, "/dɪˈzaɪn/", "thiết kế", "I love the design of this building."),
        ("architect", N, "/ˈɑːkɪtekt/", "kiến trúc sư", "A French architect designed it."),
        ("build", V, "/bɪld/", "xây dựng", "They plan to build a new bridge."),
        ("century", N, "/ˈsentʃəri/", "thế kỷ", "The temple is from the 11th century."),
        ("ancient", ADJ, "/ˈeɪnʃənt/", "cổ xưa", "Hue has many ancient buildings."),
        ("famous", ADJ, "/ˈfeɪməs/", "nổi tiếng", "Hoi An is famous for its lanterns."),
        ("height", N, "/haɪt/", "chiều cao", "What is the height of the tower?"),
        ("style", N, "/staɪl/", "phong cách", "The house is built in French style."),
        ("balcony", N, "/ˈbælkəni/", "ban công", "We drink tea on the balcony."),
        ("ceiling", N, "/ˈsiːlɪŋ/", "trần nhà", "The ceiling is painted blue."),
        ("entrance", N, "/ˈentrəns/", "lối vào", "The entrance is on the left."),
        ("courtyard", N, "/ˈkɔːtjɑːd/", "sân trong", "Children play in the courtyard."),
        ("pagoda", N, "/pəˈɡəʊdə/", "ngôi chùa", "This pagoda is small but famous."),
        ("restore", V, "/rɪˈstɔː/", "trùng tu", "Workers restore the old gate."),
        ("heritage", N, "/ˈherɪtɪdʒ/", "di sản", "Hoi An is a World Heritage site."),
    ]),
    "Nông sản và thực phẩm": (["Trái cây miền Tây", "Ở chợ nổi"], [
        ("farmer", N, "/ˈfɑːmə/", "nông dân", "The farmer gets up very early."),
        ("farm", N, "/fɑːm/", "trang trại", "They have a small fish farm."),
        ("harvest", N, "/ˈhɑːvɪst/", "mùa gặt, thu hoạch", "The rice harvest is in October."),
        ("crop", N, "/krɒp/", "cây trồng, vụ mùa", "Rice is the main crop here."),
        ("grow", V, "/ɡrəʊ/", "trồng", "They grow mangoes in the delta."),
        ("mango", N, "/ˈmæŋɡəʊ/", "quả xoài", "This mango is very sweet."),
        ("coconut", N, "/ˈkəʊkənʌt/", "quả dừa", "I drank fresh coconut water."),
        ("pineapple", N, "/ˈpaɪnæpl/", "quả dứa", "Cut the pineapple into small pieces."),
        ("watermelon", N, "/ˈwɔːtəmelən/", "dưa hấu", "We eat watermelon at Tet."),
        ("durian", N, "/ˈdʊəriən/", "sầu riêng", "Durian has a strong smell."),
        ("corn", N, "/kɔːn/", "ngô", "Grilled corn is a popular snack."),
        ("potato", N, "/pəˈteɪtəʊ/", "khoai tây", "Peel the potato first."),
        ("carrot", N, "/ˈkærət/", "cà rốt", "Rabbits love a fresh carrot."),
        ("onion", N, "/ˈʌnjən/", "củ hành", "Chop the onion finely."),
        ("garlic", N, "/ˈɡɑːlɪk/", "tỏi", "Fry the garlic until golden."),
        ("chilli", N, "/ˈtʃɪli/", "ớt", "This chilli is too hot for me."),
        ("herb", N, "/hɜːb/", "rau thơm", "Basil is a common herb in pho."),
        ("fresh", ADJ, "/freʃ/", "tươi", "Buy fresh fish at the market."),
        ("ripe", ADJ, "/raɪp/", "chín", "These bananas are not ripe yet."),
        ("sweet", ADJ, "/swiːt/", "ngọt", "Sugar cane juice is sweet."),
        ("sour", ADJ, "/ˈsaʊə/", "chua", "Tamarind soup tastes sour."),
        ("bitter", ADJ, "/ˈbɪtə/", "đắng", "Bitter melon is good for your health."),
        ("spicy", ADJ, "/ˈspaɪsi/", "cay", "I love spicy food."),
        ("floating market", N, "/ˈfləʊtɪŋ ˈmɑːkɪt/", "chợ nổi", "Cai Rang floating market starts at dawn.", "col"),
        ("kilo", N, "/ˈkiːləʊ/", "ký (kilôgam)", "How much is a kilo of mangoes?"),
        ("organic", ADJ, "/ɔːˈɡænɪk/", "hữu cơ", "Organic vegetables cost more."),
        ("pick", V, "/pɪk/", "hái", "We pick strawberries in Da Lat."),
        ("export", N, "/ˈekspɔːt/", "hàng xuất khẩu", "Rice is our main export."),
        ("taste", V, "/teɪst/", "nếm", "Taste the soup before you add salt."),
        ("rice paddy", N, "/raɪs ˈpædi/", "ruộng lúa", "Ducks swim in the rice paddy.", "col"),
    ]),
}
